# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 175)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_address = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_address.setGeometry(QtCore.QRect(20, 10, 601, 20))
        self.lineEdit_address.setReadOnly(True)
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.pushButton_open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open.setGeometry(QtCore.QRect(650, 10, 75, 23))
        self.pushButton_open.setObjectName("pushButton_open")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 101, 16))
        self.label.setObjectName("label")
        self.label_originallength = QtWidgets.QLabel(self.centralwidget)
        self.label_originallength.setGeometry(QtCore.QRect(130, 50, 101, 16))
        self.label_originallength.setObjectName("label_originallength")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(30, 80, 101, 16))
        self.label_1.setObjectName("label_1")
        self.label_droplength = QtWidgets.QLabel(self.centralwidget)
        self.label_droplength.setGeometry(QtCore.QRect(130, 80, 101, 16))
        self.label_droplength.setObjectName("label_droplength")
        self.lineEdit_times = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_times.setGeometry(QtCore.QRect(250, 50, 113, 20))
        self.lineEdit_times.setObjectName("lineEdit_times")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 130, 701, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 50, 41, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_draw = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_draw.setGeometry(QtCore.QRect(380, 50, 75, 23))
        self.pushButton_draw.setObjectName("pushButton_draw")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "STMImageConverter"))
        self.pushButton_open.setText(_translate("MainWindow", "OPEN"))
        self.label.setText(_translate("MainWindow", "OriginalLength:"))
        self.label_originallength.setText(_translate("MainWindow", "NULL"))
        self.label_1.setText(_translate("MainWindow", "DropLength"))
        self.label_droplength.setText(_translate("MainWindow", "NULL"))
        self.lineEdit_times.setText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "Steps:"))
        self.pushButton_draw.setText(_translate("MainWindow", "DRAW"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
